name: test
on: [push, pull_request]
env:
  CI: true
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node_version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
